### ISSUE TITLE
Editor instance is not restored after leaving room and returning back to room

### ISSUE THREAD

**Issue by mslevis** [CS3219-AY2324S1/ay2324s1-course-assessment-g57#33]
### How to Replicate *
1. User A joins matching queue
2. User B joins matching queue
3. Both users are directed to the collab space
4. User A leaves room by clicking the 'Leave Room' button
5. User A clicks 'Collaborate' on the Nav Bar
6. Editor is no longer in sync with User B

### Current vs Expected behavior *
Following the steps from the previous section, I expected user A's editor to be still in sync with user B, even after leaving the room

### Additional Context
- To discuss what is the expected behavior upon leaving the room and functionality of Collaborate button in Nav Bar

**Comment by mslevis** [comment]
Marked as duplicate. This issue is a result of #36

**Comment by Gibson0918** [comment]
Closing this due to duplication.
